**Install Pandas**

%pip install pandas

In [2]:
%pip install -U -q pandas

Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd

**Series 1D data**

In [4]:
s = pd.Series([10, 20, 30, 40, 50], name="Marks")

In [6]:
print(type(s))

<class 'pandas.Series'>

In [7]:
print(s[0]) #accessing first element
print(s.mean())

10
30.0

In [11]:
data = {
    "Name": ["Alice", "Bob", "Charlie", "David"],
    "Age": [25, 30, 35, 40],
    "Score": [85, 90, 95, 80]
}

print(type(data))
print(data)

data_frame = pd.DataFrame(data) #data saved to data frame
print(type(data_frame))

<class 'dict'>
{'Name': ['Alice', 'Bob', 'Charlie', 'David'], 'Age': [25, 30, 35, 40], 'Score': [85, 90, 95, 80]}
<class 'pandas.DataFrame'>

In [12]:
data_frame.head() #first 5 rows of data frame

      Name  Age  Score
0    Alice   25     85
1      Bob   30     90
2  Charlie   35     95
3    David   40     80

In [14]:
#Saving a data frame to csv file
data_frame.to_csv("data_sample.csv")

In [15]:
#read data from csv file
df = pd.read_csv("data_sample.csv")

In [17]:
df.head() #first 5 rows of the read data frame

   Unnamed: 0     Name  Age  Score
0           0    Alice   25     85
1           1      Bob   30     90
2           2  Charlie   35     95
3           3    David   40     80

In [18]:
df = pd.read_csv("diabetes.csv")

In [19]:
df.head() #first 5 rows of the read data frame

,id,chol,stab.glu,hdl,ratio,glyhb,location,age,gender,height,weight,frame,bp.1s,bp.1d,bp.2s,bp.2d,waist,hip,time.ppn
0,1000,203.0,82,56.0,3.6,4.31,Buckingham,46,female,62.0,121.0,medium,118.0,59.0,NaN,NaN,29.0,38.0,720.0
1,1001,165.0,97,24.0,6.9,4.44,Buckingham,29,female,64.0,218.0,large,112.0,68.0,NaN,NaN,46.0,48.0,360.0
2,1002,228.0,92,37.0,6.2,4.64,Buckingham,58,female,61.0,256.0,large,190.0,92.0,185.0,92.0,49.0,57.0,180.0
3,1003,78.0,93,12.0,6.5,4.63,Buckingham,67,male,67.0,119.0,large,110.0,50.0,NaN,NaN,33.0,38.0,480.0
4,1005,249.0,90,28.0,8.9,7.72,Buckingham,64,male,68.0,183.0,medium,138.0,80.0,NaN,NaN,44.0,41.0,300.0

In [22]:
#saving a dataframe to csv file
data_frame.to_csv("data_sample.csv", index=False) #index=False to avoid saving the index column

In [23]:
df.shape

(403, 19)

In [24]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 403 entries, 0 to 402
Data columns (total 19 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   id        403 non-null    int64
 1   chol      402 non-null    float64
 2   stab.glu  403 non-null    int64
 3   hdl       402 non-null    float64
 4   ratio     402 non-null    float64
 5   glyhb     390 non-null    float64
 6   location  403 non-null    str
 7   age       403 non-null    int64
 8   gender    403 non-null    str
 9   height    398 non-null    float64
 10  weight    402 non-null    float64
 11  frame     391 non-null    str
 12  bp.1s     398 non-null    float64
 13  bp.1d     398 non-null    float64
 14  bp.2s     141 non-null    float64
 15  bp.2d     141 non-null    float64
 16  waist     401 non-null    float64
 17  hip       401 non-null    float64
 18  time.ppn  400 non-null    float64
dtypes: float64(13), int64(3), str(3)
memory usage: 59.9 KB

**Selecting the data**

In [28]:
#Printing single column
print(df[["chol"]]) #printing single column

      chol
0    203.0
1    165.0
2    228.0
3     78.0
4    249.0
..     ...
398  296.0
399  284.0
400  194.0
401  199.0
402  159.0

[403 rows x 1 columns]

In [30]:
#multiple columns
print(df[["chol", "age"]]) #printing multiple columns

      chol  age
0    203.0   46
1    165.0   29
2    228.0   58
3     78.0   67
4    249.0   64
..     ...  ...
398  296.0   53
399  284.0   51
400  194.0   29
401  199.0   41
402  159.0   68

[403 rows x 2 columns]

In [31]:
#row selection
print(df.iloc[0]) #printing first row

id                1000
chol             203.0
stab.glu            82
hdl               56.0
ratio              3.6
glyhb             4.31
location    Buckingham
age                 46
gender          female
height            62.0
weight           121.0
frame           medium
bp.1s            118.0
bp.1d             59.0
bp.2s              NaN
bp.2d              NaN
waist             29.0
hip               38.0
time.ppn         720.0
Name: 0, dtype: object

In [33]:
sample_df = df.iloc[0:5] #selecting first 5 rows

In [36]:
age = df[df["age"] > 50] #selecting rows where age is greater than 50
print(age)

        id   chol  stab.glu    hdl  ratio      glyhb    location  age  gender  \
2     1002  228.0        92   37.0    6.2   4.640000  Buckingham   58  female
3     1003   78.0        93   12.0    6.5   4.630000  Buckingham   67    male
4     1005  249.0        90   28.0    8.9   7.720000  Buckingham   64    male
9     1022  263.0        89   40.0    6.6   5.780000  Buckingham   55  female
10    1024  242.0        82   54.0    4.5   4.770000      Louisa   60  female
..     ...    ...       ...    ...    ...        ...         ...  ...     ...
396  41501  216.0        84   64.0    3.4        NaN      Louisa   54  female
397  41503  301.0        90  118.0    2.6   4.280000      Louisa   89  female
398  41506  296.0       369   46.0    6.4  16.110001      Louisa   53    male
399  41507  284.0        89   54.0    5.3   4.390000      Louisa   51  female
402  41756  159.0        88   79.0    2.0        NaN      Louisa   68  female

     height  weight   frame  bp.1s  bp.1d  bp.2s  bp.2d  waist   hip  time.ppn
2      61.0   256.0   large  190.0   92.0  185.0   92.0   49.0  57.0     180.0
3      67.0   119.0   large  110.0   50.0    NaN    NaN   33.0  38.0     480.0
4      68.0   183.0  medium  138.0   80.0    NaN    NaN   44.0  41.0     300.0
9      63.0   202.0   small  108.0   72.0    NaN    NaN   45.0  50.0     240.0
10     65.0   156.0  medium  130.0   90.0  130.0   90.0   39.0  45.0     300.0
..      ...     ...     ...    ...    ...    ...    ...    ...   ...       ...
396    66.0   168.0  medium  132.0   90.0  126.0   80.0   38.0  42.0     330.0
397    61.0   115.0  medium  218.0   90.0  238.0   90.0   31.0  41.0     210.0
398    69.0   173.0  medium  138.0   94.0  130.0   94.0   35.0  39.0     210.0
399    63.0   154.0  medium  140.0  100.0  146.0  102.0   32.0  43.0     180.0
402    64.0   220.0  medium  100.0   72.0    NaN    NaN   49.0  58.0     900.0

[161 rows x 19 columns]

In [37]:
print("Average Age:", df["age"].mean()) #average age

Average Age: 46.851116625310176